### ISSUE TITLE
Sadiyeah

### ISSUE THREAD

**Issue by zamattiac** [CenterForOpenScience/ROSIEBot#84]

**Comment by sf2ne** [comment]
I take offense to this.

**Comment by zamattiac** [comment]
@sf2ne +1

**Comment by sf2ne** [comment]
![tumblr_inline_nqtaiaclw31rxa7hy_500](https://cloud.githubusercontent.com/assets/16869216/17368512/52307244-5962-11e6-8e45-28b1e96c2794.gif)

**Comment by zamattiac** [comment]
@sf2ne 
![image](https://cloud.githubusercontent.com/assets/15851093/17368524/6b23e24a-5962-11e6-8686-c433989b525c.png)

**Comment by zamattiac** [comment]
# _*\* ~~~SADIYEAH IS MEAN ~~~**_

**Comment by zamattiac** [comment]
# •?((¯°·._.• ⓢⓐⓓⓘⓨⓔⓐⓗ ⓘⓢ ⓜⓔⓐⓝ •._.·°¯))؟•
